system_params:
  wandb_api_key: null
  data_file_path: "data.npz"
  data_url: null

net_params:
  transition_model_params:
    latent_dim: 128
    n_layers: 3
    n_heads: 4
    pe_wavelength_range: [1, 2048]
  state_encoder_params:
    layer_sizes: [1024, 512, 512]
  action_encoder_params:
    layer_sizes: [512, 1024, 512]
  state_decoder_params:
    layer_sizes: [1024, 512, 512]
  action_decoder_params:
    layer_sizes: [512, 1024, 512]

action_space_size: 1.0
state_space_size: 2.0

loss_params:
  loss_weights:
    state_reconstruction: 1.0
    action_reconstruction: 1.0
    state_coverage: 0.1
    action_coverage: 0.1
    condensation: 10.0
    transition: 0.001
    smoothness: 0.1
    consistency: 1.0
  state_coverage_loss_params:
    latent_samples: 4096
    selection_tail_size: 4
    far_sample_count: 64
    pushing_sample_size: 16
  action_coverage_loss_params:
    latent_samples: 1024
    selection_tail_size: 4
    far_sample_count: 16
    pushing_sample_size: 64
  consistency_loss_params:
    state_samples: 2048
    action_samples: 2048

batching_params:
  transition_warmup_epochs: 1
  encoder_warmup_epochs: 64
  transition_finetune_epochs: 8
  encoder_batch_size: 4096
  transition_batch_size: 128
  encoder_grad_skips: 4
  encoder_epochs: 1
  transition_epochs: 1
  train_epochs: 256
  test_epoch_steps: 8
  epoch_state_actions: 250000
  epoch_trajectories: 25000
  train_proportion: 0.8

optimizer_params:
  encoder_lr: 0.0001
  transition_lr: 0.0001